name: ðŸ«£ Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ðŸ¥ Checkout
      uses: actions/checkout@v4
    - name: â˜•ï¸ JDKv17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: âš¡ï¸ +x gradlew
      run: chmod +x gradlew
    - name: ðŸŽª Secrets
      if: success()
      # TODO: override iff it doesn't exist
      # developers.google.com/android/guides/google-services-plugin#adding_the_json_file
      run: |
        mkdir -p app/src/debug
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/src/debug/google-services.json
    - name: ðŸš‚ Build
      if: success()
      run: ./gradlew assembleWebsiteFullDebug --info --warning-mode all

