name: ğŸ«£ Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ğŸ¥ Checkout
      uses: actions/checkout@v4
    - name: â˜•ï¸ JDKv17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: âš¡ï¸ +x gradlew
      run: chmod +x gradlew
    - name: ğŸª Secrets
      if: success()
      # TODO: override iff it doesn't exist
      # developers.google.com/android/guides/google-services-plugin#adding_the_json_file
      run: |
        mkdir -p app/src/debug
        cat <<EOF > app/src/debug/google-services.json
        $GSCV_TEST_JSON
        EOF
        wc -lwm app/src/debug/google-services.json
      env:
        GSCV_TEST_JSON: ${{ secrets.GOOGLE_SERVICES_TEST_JSON }}
    - name: ğŸš‚ Assemble
      if: success()
      run: |
        # Force compileSdk 36 for all variants
        ./gradlew \
          assembleWebsiteFullDebug \
          --info \
          --warning-mode all
