name: âš›ï¸ Native Sym

on:
  #push:
    #tags:
      #- "v*"
  # docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  # docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
  # docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:
    # github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    # docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
    inputs:
      commit:
        description: 'commit sha'
        default: ''
        required: true

jobs:
  # from: github.com/Menci/acme/blob/5a12d53/action.yml
  Symbols:
    name: ğŸ”¥ Firebase
    runs-on: ubuntu-latest

    env:
      COMMIT: ${{ github.event.inputs.commit || github.sha }}

    steps:
      - name: ğŸ¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ± Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: ğŸ¨ Deps
        run: npm install -g firebase-tools

      - name: ğŸš€ Firestack AAR
        run: |
          # wget opts: superuser.com/a/689340
          wgetopts="--tries=3 --retry-on-http-error=404 --waitretry=3 --no-dns-cache"
          wget $wgetopts "https://jitpack.io/com/github/celzero/firestack/${COMMIT:0:10}/firestack-${COMMIT:0:10}-debug.aar" -O "firestack.aar"
          ls -ltr .
          unzip ./firestack.aar
          firebase crashlytics:symbols:upload --app=${{ secrets.FIREBASE_APP_ID_ANDROID }} --debug --generator=csym jni/
        shell: bash
        env:
          COMMIT: ${{ env.COMMIT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          


